(defun stex ()
  (interactive)
  (split-window-right)
  (windmove-right)
  (setq fname "~/.tex/sample.tex")
  (find-file-read-only fname))

(defun ctex ()
  (interactive)
  (save-buffer)
  (shell-command "ctex"))

;;(defun ctex ()
;;  (interactive)
;;  (setq fname (file-name-nondirectory (buffer-file-name)))
;;  (setq com (message "ctex %s" fname))
;;  (shell-command com))
